import vk_api
from vk_api.longpoll import VkLongPoll, VkEventType
import random
import json

import Students
from Students import student_keyboard, studentpractica_page_1_keyboard, studentpractica_page_2_keyboard, studentpractica_page_3_keyboard, studentpractica_page_4_keyboard
import Role
from Role import role_keyboard
import Work_sibguti
from Work_sibguti import sibguti_keyboard
import Graduate
from Graduate import graduate_keyboard
import courses_and_training
from courses_and_training import courses_and_training_keyboard
import WorkStudent
from WorkStudent import workstudent_keyboard, student_or_graduate_keyboard , workgraduate_keyboard
import Internship
from Internship import internship_keyboard